---
- name: install required packages
  apt:
    pkg:
    - language-pack-ja
    - manpages-ja
    - manpages-ja-dev

- name: check locale
  command: localectl status
  register: localectl_result
  check_mode: no
  changed_when: false

- name: change locale
  command: localectl set-locale ja_JP.UTF-8
  when: "'LANG=ja_JP.UTF-8' not in localectl_result.stdout"

- name: set timezone
  timezone:
    name: Asia/Tokyo
